version: "3.9"
services:

  api:
    build: ./api
    ports:
      - "80:6000"
    environment:
      PG_CONNECTION_STRING: postgress://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5432/${POSTGRES_DB}
      PORT: ${APIPORT}
    volumes:
     - ./api/src:/usr/app/src
    depends_on:
     - pg

  pg:
   container_name: ${POSTGRES_DB}
   image: postgres:latest
   ports:
    - 5432:5432
   environment:
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
   volumes:
    - ./db/data/postgres:/var/lib/postgresql/data

